package com.telemedconnect.patient.lists

import com.telemedconnect.patient.R
import com.telemedconnect.patient.data.models.DashboardAction

object DashboardActionsList {
    var items_general_needs = listOf(
        DashboardAction(
            R.string.request_emergency_service,
            R.string.request_emergency_service_desc_long,
            R.string.request_emergency_service_desc_short,
            R.drawable.ic_emergency,
            R.drawable.bg_ds_emergency_service
        ),
        DashboardAction(
            R.string.request_urgent_care,
            R.string.request_urgent_care_desc_long,
            R.string.request_urgent_care_desc_short,
            R.drawable.ic_urgent_care,
            R.drawable.bg_ds_urgent_care
        ),
        DashboardAction(
            R.string.talk_to_a_doctor,
            R.string.talk_to_a_doctor_desc_long,
            R.string.talk_to_a_doctor_desc_short,
            R.drawable.ic_talk_to_doctor,
            R.drawable.bg_ds_talk_to_doctor
        ),
        DashboardAction(
            R.string.request_physical_consultation,
            R.string.request_physical_consultation_desc_long,
            R.string.request_physical_consultation_desc_short,
            R.drawable.ic_physical_consultation,
            R.drawable.bg_ds_physical_consultation
        ),
        DashboardAction(
            R.string.locate_a_pharmacy,
            R.string.locate_a_pharmacy_desc_long,
            R.string.locate_a_pharmacy_desc_short,
            R.drawable.ic_pharmacy,
            R.drawable.bg_ds_locate_pharmacy
        ),
        DashboardAction(
            R.string.find_a_health_center,
            R.string.find_a_health_center_desc_long,
            R.string.find_a_health_center_desc_short,
            R.drawable.ic_health_center,
            R.drawable.bg_ds_health_center
        ),
        DashboardAction(
            R.string.book_an_appointment,
            R.string.book_an_appointment_desc_long,
            R.string.book_an_appointment_desc_short,
            R.drawable.ic_book_appointment,
            R.drawable.bg_ds_book_appointment
        ),
        DashboardAction(
            R.string.health_qa,
            R.string.health_qa_desc_long,
            R.string.health_qa_desc_short,
            R.drawable.ic_qna,
            R.drawable.bg_ds_health_qna
        ),
        DashboardAction(
            R.string.symptoms_and_assessment,
            R.string.symptoms_and_assessment_desc_long,
            R.string.symptoms_and_assessment_desc_short,
            R.drawable.ic_symptoms_assessment,
            R.drawable.bg_ds_symptoms_assessment
        )
    )

    var items_special_needs = listOf(
        DashboardAction(
            R.string.children_health,
            R.string.children_health_desc_long,
            R.string.children_health_desc_short,
            R.drawable.ic_child,
            R.drawable.bg_ds_chlidren_health
        ),
        DashboardAction(
            R.string.senior_health,
            R.string.senior_health_desc_long,
            R.string.senior_health_desc_short,
            R.drawable.ic_senior,
            R.drawable.bg_ds_senior_health
        ),
        DashboardAction(
            R.string.women_health,
            R.string.women_health_desc_long,
            R.string.women_health_desc_short,
            R.drawable.ic_women,
            R.drawable.bg_ds_women_health
        ),
        DashboardAction(
            R.string.men_health,
            R.string.men_health_desc_long,
            R.string.men_health_desc_short,
            R.drawable.ic_men,
            R.drawable.bg_ds_men_health
        ),
        DashboardAction(
            R.string.order_a_lab_test,
            R.string.order_a_lab_test_desc_long,
            R.string.order_a_lab_test_desc_short,
            R.drawable.ic_lab_test,
            R.drawable.bg_ds_lab_test
        ),
        DashboardAction(
            R.string.new_health_concern,
            R.string.new_health_concern_desc_long,
            R.string.new_health_concern_desc_short,
            R.drawable.ic_new_health_concern,
            R.drawable.bg_ds_new_health_concern
        ),
        DashboardAction(
            R.string.routine_checkup,
            R.string.routine_checkup_desc_long,
            R.string.routine_checkup_desc_short,
            R.drawable.ic_routine_checkup,
            R.drawable.bg_ds_routine_checkup
        ),
        DashboardAction(
            R.string.chronic_condition,
            R.string.chronic_condition_desc_long,
            R.string.chronic_condition_desc_short,
            R.drawable.ic_chronic_condition,
            R.drawable.bg_ds_chronic_condition
        ),
        DashboardAction(
            R.string.prescription_or_refills,
            R.string.prescription_or_refills_desc_long,
            R.string.prescription_or_refills_desc_short,
            R.drawable.ic_prescription_refill,
            R.drawable.bg_ds_prescription_refill
        ),
        DashboardAction(
            R.string.mental_health,
            R.string.mental_health_desc_long,
            R.string.mental_health_desc_short,
            R.drawable.ic_mental_health,
            R.drawable.bg_ds_mental_health
        ),
        DashboardAction(
            R.string.covid_19_symptoms,
            R.string.covid_19_symptoms_desc_long,
            R.string.covid_19_symptoms_desc_short,
            R.drawable.ic_covid_19_symptoms,
            R.drawable.bg_ds_covid_19_symptoms
        ),
        DashboardAction(
            R.string.sexual_health_education,
            R.string.sexual_health_education_desc_long,
            R.string.sexual_health_education_desc_short,
            R.drawable.ic_sexual_health,
            R.drawable.bg_ds_sexual_health
        ),
        DashboardAction(
            R.string.other_medical_reasons,
            R.string.other_medical_reasons_desc_long,
            R.string.other_medical_reasons_desc_short,
            R.drawable.ic_other_medical_reasons,
            R.drawable.bg_ds_other_medical_reasons
        )
    )
}